(function(){try{var G=(typeof globalThis!=="undefined")?globalThis:(typeof self!=="undefined"?self:this);
if(!G||G.__sandRpcRewrite)return;G.__sandRpcRewrite=1;
var F="agent.v1.AgentService/Run",T="aiserver.v1.InferenceService/Stream";
function rw(u){return(typeof u==="string"&&u.indexOf(F)>=0)?u.split(F).join(T):u}
function sandHdr(h){if(!h)return;function set(k,v){try{if(typeof h.set==="function")h.set(k,v);else{h[k]=v;h[k.toLowerCase()]=v}}catch(e){}}set("x-cursor-client-type","sand");set("x-cursor-client-version","0.18.0");set("x-sand-box-namespace","prod")}
function isCursorHdr(h,extra){try{var parts=extra?[String(extra)]:[];if(h){if(typeof h.get==="function")parts.push(h.get(":path")||"",h.get("path")||"",h.get(":authority")||"",h.get("host")||"",h.get("url")||"");else parts.push(h[":path"]||"",h.path||"",h[":authority"]||"",h.host||"",h.url||"",h.hostname||"",h.href||"")}return /cursor\.sh|InferenceService|AgentService/i.test(parts.join(" "))}catch(e){return 0}}
function rwHdr(h){if(!h)return;try{if(typeof h.get==="function"&&typeof h.set==="function"){var p=h.get(":path")||h.get("path");if(typeof p==="string"&&p.indexOf(F)>=0){h.set(h.get(":path")?":path":"path",rw(p));}}else{if(typeof h[":path"]==="string")h[":path"]=rw(h[":path"]);if(typeof h.path==="string")h.path=rw(h.path);if(typeof h.url==="string")h.url=rw(h.url);}}catch(e){}if(isCursorHdr(h))sandHdr(h)}
function isAgentRun(svc,meth){try{var tn=svc&&svc.typeName,nm=meth&&meth.name,I=meth&&meth.I,itn=I&&I.typeName;if(tn==="agent.v1.AgentService"&&nm==="Run")return 1;if(nm==="Stream"&&itn==="agent.v1.AgentClientMessage")return 1;return 0}catch(e){return 0}}
function retarget(svc,meth){return[Object.assign({},svc,{typeName:"aiserver.v1.InferenceService"}),Object.assign({},meth,{name:"Stream",kind:1})]}
function unwrapThen(input,fn){try{if(input&&typeof input[Symbol.asyncIterator]==="function"){return Promise.resolve(input[Symbol.asyncIterator]().next()).then(function(r){return fn(r&&r.value)})}}catch(e){}return fn(input)}
function u8(s){s=String(s);try{if(typeof TextEncoder!=="undefined")return new TextEncoder().encode(s)}catch(e){}try{if(typeof Buffer!=="undefined")return Uint8Array.from(Buffer.from(s,"utf8"))}catch(e){}var a=[];for(var i=0;i<s.length;i++){var c=s.charCodeAt(i);if(c<128)a.push(c);else{var e=unescape(encodeURIComponent(s));a=[];for(var j=0;j<e.length;j++)a.push(e.charCodeAt(0));break}}return new Uint8Array(a)}
function u8s(b){try{return new TextDecoder("utf-8").decode(b)}catch(e){var s="";for(var i=0;i<b.length;i++)s+=String.fromCharCode(b[i]);try{return decodeURIComponent(escape(s))}catch(e2){return s}}}
function uv(n){var a=[];n=n>>>0;while(n>127){a.push((n&127)|128);n=n>>>7}a.push(n);return a}
function cat(xs){var conv=[],i,n=0,x;for(i=0;i<xs.length;i++){x=xs[i];if(!(x instanceof Uint8Array))x=new Uint8Array(x);conv.push(x);n+=x.length}var o=new Uint8Array(n),p=0;for(i=0;i<conv.length;i++){o.set(conv[i],p);p+=conv[i].length}return o}
function tag(f,w){return new Uint8Array(uv((f<<3)|w))}
function bstr(f,s){var b=u8(s);return cat([tag(f,2),new Uint8Array(uv(b.length)),b])}
function bmsg(f,inner){return cat([tag(f,2),new Uint8Array(uv(inner.length)),inner])}
function bvar(f,n){if(!n)return new Uint8Array(0);return cat([tag(f,0),new Uint8Array(uv(n))])}
function bbool(f,v){return v?cat([tag(f,0),new Uint8Array([1])]):new Uint8Array(0)}
function toPlain(msg){try{if(msg&&typeof msg.toJson==="function")return msg.toJson()}catch(e){}try{if(msg&&typeof msg.toJsonString==="function")return JSON.parse(msg.toJsonString())}catch(e){}return msg&&typeof msg==="object"?msg:{}}
function histText(obj){if(!obj)return"";if(typeof obj.text==="string"&&obj.text)return obj.text;var c=obj.content;if(typeof c==="string")return c;var s="",i,p,t;if(Array.isArray(c)){for(i=0;i<c.length;i++){p=c[i];if(!p)continue;if(typeof p.text==="string")s+=p.text;else if(p.text&&typeof p.text.text==="string")s+=p.text.text;else if(p.content){t=p.content.text||p.content.value;if(typeof t==="string")s+=t;else if(t&&typeof t.text==="string")s+=t.text}}return s}if(c&&typeof c==="object"){if(typeof c.text==="string")return c.text;if(c.text&&typeof c.text.text==="string")return c.text.text;if(c.value&&typeof c.value.text==="string")return c.value.text}return""}
function addHist(hist,msgs){var list=hist&&(hist.messages||hist);if(!Array.isArray(list))return;for(var i=0;i<list.length;i++){var hm=list[i]||{},m=hm.message||hm,u=m.user||m.userMessage,a=m.assistant||m.assistantMessage,tx;if(u){tx=histText(u);if(tx)msgs.push({r:1,t:tx})}else if(a){tx=histText(a);if(tx)msgs.push({r:2,t:tx})}}}
function specFromAgent(msg){var p=toPlain(msg),run=p.runRequest||p.run_request||p.prewarmRequest||p.prewarm_request;if(!run&&p.message){var c=p.message.case,v=p.message.value;if(c==="runRequest"||c==="run_request"||c==="prewarmRequest"||c==="prewarm_request")run=toPlain(v)}run=run||p;var rm=run.requestedModel||run.requested_model||run.modelDetails||run.model_details||{};var mid=rm.modelId||rm.model_id||"grok-4.5";var maxm=rm.maxMode!=null?!!rm.maxMode:rm.max_mode!=null?!!rm.max_mode:true;var params=rm.parameters||[];if(!params.length)params=[{id:"effort",value:"high"},{id:"fast",value:"true"}];var sys=run.customSystemPrompt||run.custom_system_prompt||"";var msgs=[];if(sys)msgs.push({r:4,t:sys});var act=run.action||{};if(act.case==="userMessageAction"||act.case==="user_message_action")act=toPlain(act.value)||{};var uma=act.userMessageAction||act.user_message_action||((act.userMessage||act.user_message)?act:null);if(uma){addHist(uma.conversationHistory||uma.conversation_history,msgs);var pre=uma.prependUserMessages||uma.prepend_user_messages||[];for(var i=0;i<pre.length;i++){var t=pre[i]&&pre[i].text;if(t)msgs.push({r:1,t:t})}var um=uma.userMessage||uma.user_message;var ut=um&&um.text;if(ut)msgs.push({r:1,t:ut})}if(!msgs.some(function(x){return x.r===1||x.r===2}))msgs.push({r:1,t:"hello"});return{cid:run.conversationId||run.conversation_id||"",mid:mid,maxm:maxm,params:params,msgs:msgs}}
function encStreamReq(msg){var spec=specFromAgent(msg),parts=[],i,j,pv,id,val,rm;for(i=0;i<spec.msgs.length;i++)parts.push(bmsg(1,cat([bvar(1,spec.msgs[i].r),bstr(2,spec.msgs[i].t)])));rm=[bstr(1,spec.mid),bbool(2,spec.maxm)];for(j=0;j<spec.params.length;j++){pv=spec.params[j]||{};id=pv.id||pv.ID;val=pv.value!=null?pv.value:"";if(id)rm.push(bmsg(3,cat([bstr(1,id),bstr(2,String(val))])))}parts.push(bmsg(7,cat(rm)));if(spec.cid)parts.push(bstr(8,spec.cid));return cat(parts)}
function rv(u,st){var n=0,s=0,b;do{b=u[st.i++];n=n|((b&127)<<s);s+=7}while(b&128&&st.i<u.length);return n>>>0}
function skip(u,st,w){if(w===0)rv(u,st);else if(w===1)st.i+=8;else if(w===5)st.i+=4;else if(w===2){var l=rv(u,st);st.i+=l}else st.i=u.length}
function decLen(u){var st={i:0},f,w,l,sl,p,out={};while(st.i<u.length){var t=rv(u,st);f=t>>>3;w=t&7;if(w===2){l=rv(u,st);sl=u.subarray(st.i,st.i+l);st.i+=l;if(f===1){p=decPart(sl);if(p.text)out.text=p.text;if(p.final)out.final=1}else if(f===9){p=decPart(sl);if(p.text)out.think=p.text}else if(f===8){out.err=decStr1(sl)||"inference error"}}else skip(u,st,w)}return out}
function decPart(u){var st={i:0},o={},f,w,l;while(st.i<u.length){var t=rv(u,st);f=t>>>3;w=t&7;if(w===0){var v=rv(u,st);if(f===2)o.final=!!v}else if(w===2){l=rv(u,st);if(f===1)o.text=u8s(u.subarray(st.i,st.i+l));st.i+=l}else skip(u,st,w)}return o}
function decStr1(u){var st={i:0},f,w,l;while(st.i<u.length){var t=rv(u,st);f=t>>>3;w=t&7;if(w===2){l=rv(u,st);if(f===1)return u8s(u.subarray(st.i,st.i+l));st.i+=l}else skip(u,st,w)}return""}
function infToAgent(inf){if(!inf)return{interactionUpdate:{heartbeat:{}}};if(inf.err)return{interactionUpdate:{textDelta:{text:"[sand] "+inf.err}}};if(inf.think)return{interactionUpdate:{thinkingDelta:{text:inf.think}}};if(inf.text)return{interactionUpdate:{textDelta:{text:inf.text}}};return{interactionUpdate:{heartbeat:{}}}}
function asAgent(origO,j){try{if(origO&&typeof origO.fromJson==="function")return origO.fromJson(j)}catch(e){}return j}
function wrapTurnEnd(resp,origO){if(!resp||!resp.message||typeof resp.message[Symbol.asyncIterator]!=="function")return resp;var src=resp.message,done=0;resp.message=(async function*(){try{for await(var m of src){if(m!=null)yield m}}finally{if(!done){done=1;try{yield asAgent(origO,{interactionUpdate:{turnEnded:{}}})}catch(e){}}}})();return resp}
function doRewrite(streamFn,svc,meth,a,b,c,input,d){try{sandHdr(c)}catch(e){}if(!isAgentRun(svc,meth))return streamFn(svc,meth,a,b,c,input,d);var origO=meth.O;var x=retarget(svc,meth);svc=x[0];meth=x[1];return unwrapThen(input,function(msg){var bin=encStreamReq(msg);var FakeI={typeName:"aiserver.v1.InferenceStreamRequest",toBinary:function(){return bin},fromBinary:function(){return{_bin:bin,toBinary:function(){return bin}}},fromJson:function(){return{_bin:bin,toBinary:function(){return bin}}}};var FakeO={typeName:"aiserver.v1.InferenceStreamResponse",fromBinary:function(bytes){try{return asAgent(origO,infToAgent(decLen(bytes instanceof Uint8Array?bytes:new Uint8Array(bytes))))}catch(e){return asAgent(origO,{interactionUpdate:{textDelta:{text:"[sand] "+((e&&e.message)||e)}}})}},fromJson:function(j){return asAgent(origO,j)}};meth=Object.assign({},meth,{I:FakeI,O:FakeO,kind:1,name:"Stream"});var packed={_bin:bin,toBinary:function(){return bin}};return Promise.resolve(streamFn(svc,meth,a,b,c,packed,d)).then(function(resp){return wrapTurnEnd(resp,origO)})})}
G.__sandRewriteStream=function(tr,svc,meth,a,b,c,input,d){try{return doRewrite(tr.stream.bind(tr),svc,meth,a,b,c,input,d)}catch(e){return tr.stream(svc,meth,a,b,c,input,d)}};
try{if(typeof process!=="undefined"&&process.env&&process.env.SAND_RPC_TEST){G.__sandTest={enc:encStreamReq,dec:decLen,spec:specFromAgent,toAgent:infToAgent,hdr:sandHdr}}}catch(e){}
var OF=G.fetch;if(typeof OF==="function"){G.fetch=function(i,n){try{var url=typeof i==="string"?i:(i&&i.url);if(typeof i==="string")i=rw(i);else if(i&&typeof i.url==="string"&&i.url.indexOf(F)>=0){try{i=new Request(rw(i.url),i)}catch(e){}}if(n&&n.headers)rwHdr(n.headers);else if(isCursorHdr(null,url)){n=n||{};n.headers=n.headers||{};sandHdr(n.headers)}}catch(e){}return OF.call(this,i,n)}}
var XO=G.XMLHttpRequest;if(XO&&XO.prototype&&XO.prototype.open){var OO=XO.prototype.open;XO.prototype.open=function(){try{if(typeof arguments[1]==="string")arguments[1]=rw(arguments[1])}catch(e){}return OO.apply(this,arguments)}}
function patchH2(h2){if(!h2||h2.__sandRpcRewrite)return;h2.__sandRpcRewrite=1;var oc=h2.connect;if(typeof oc!=="function")return;h2.connect=function(){var s=oc.apply(this,arguments);try{var orq=s.request;s.request=function(hd){try{rwHdr(hd)}catch(e){}return orq.apply(this,arguments)}}catch(e){}return s}}
function patchHttp(h){if(!h||h.__sandRpcRewrite)return;h.__sandRpcRewrite=1;function wrap(fn){return function(opts){try{if(typeof opts==="string")arguments[0]=rw(opts);else if(opts&&typeof opts==="object"){if(typeof opts.path==="string")opts.path=rw(opts.path);if(typeof opts.href==="string")opts.href=rw(opts.href);if(typeof opts.pathname==="string")opts.pathname=rw(opts.pathname);if(typeof opts.url==="string")opts.url=rw(opts.url);if(isCursorHdr(opts.headers,opts.path||opts.host||opts.hostname||opts.href||opts.url)){if(opts.headers)sandHdr(opts.headers);else{opts.headers={};sandHdr(opts.headers)}}}}catch(e){}return fn.apply(this,arguments)}}if(typeof h.request==="function")h.request=wrap(h.request);if(typeof h.get==="function")h.get=wrap(h.get)}
function patchConnect(mod){if(!mod||mod.__sandRpcRewrite)return;if(typeof mod.createConnectTransport!=="function")return;mod.__sandRpcRewrite=1;var oct=mod.createConnectTransport;mod.createConnectTransport=function(){var tr=oct.apply(this,arguments);try{function wrapFn(fn){return function(svc,meth,a,b,c,input,d){try{return doRewrite(fn.bind(this),svc,meth,a,b,c,input,d)}catch(e){return fn.apply(this,arguments)}}}if(tr&&typeof tr.stream==="function")tr.stream=wrapFn(tr.stream);if(tr&&typeof tr.unary==="function")tr.unary=wrapFn(tr.unary)}catch(e){}return tr}}
try{var req=typeof require==="function"?require:null;if(req){try{patchH2(req("http2"))}catch(e){}try{patchHttp(req("http"))}catch(e){}try{patchHttp(req("https"))}catch(e){}try{patchConnect(req("@connectrpc/connect-node"))}catch(e){}try{var Mod=req("module");if(Mod&&Mod.prototype&&Mod.prototype.require){var oreq=Mod.prototype.require;Mod.prototype.require=function(id){var m=oreq.apply(this,arguments);try{if(id==="http2"||id==="node:http2")patchH2(m);if(id==="http"||id==="https"||id==="node:http"||id==="node:https")patchHttp(m);if(id==="@connectrpc/connect-node")patchConnect(m)}catch(e){}return m}}}catch(e){}try{var el=req("electron");if(el&&el.net&&typeof el.net.request==="function"&&!el.net.__sandRpcRewrite){el.net.__sandRpcRewrite=1;var nr=el.net.request;el.net.request=function(opts){try{if(typeof opts==="string")opts=rw(opts);else if(opts&&typeof opts.url==="string")opts.url=rw(opts.url);else if(opts&&typeof opts.path==="string")opts.path=rw(opts.path);if(opts&&isCursorHdr(opts.headers,typeof opts==="string"?opts:(opts.url||opts.path||opts.host))){if(opts.headers)sandHdr(opts.headers);else if(typeof opts==="object"){opts.headers={};sandHdr(opts.headers)}}}catch(e){}return nr.apply(this,arguments)}}}catch(e){}}}catch(e){}}catch(e){}})();
